carts/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^cart/$',views.view,name='cart'),
    url(r'^cart/(?P<id>\d+)/$',views.remove_from_cart,name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$',views.add_to_cart,name='add_to_cart'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    url(r'',include('products.urls')),
    url(r'',include('carts.urls')),
    url(r'',include('orders.urls')),
    url(r'',include('accounts.urls')),
    url(r'',include('marketing.urls')),
    url('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^checkout/$',views.checkout,name='checkout'),
    url(r'^orders/$',views.orders,name='user_orders')
]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model

from carts.models import  Cart

User=get_user_model()

STATUS_CHOICES=(
    ("Started","Started"),
    ("Abandoned","Abandoned"),
    ("Finished","Finished"),
)

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    order_id=models.CharField(max_length=120,default='ABC',unique=True)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    status=models.CharField(max_length=120,choices=STATUS_CHOICES,default="Started")

    sub_total=models.DecimalField(default=10.99,max_digits=1000,decimal_places=2)
    tax_total=models.DecimalField(default=0.00,max_digits=1000,decimal_places=2)
    final_total=models.DecimalField(default=10.99,max_digits=1000,decimal_places=2)

    timestamp=models.DateTimeField(auto_now_add=True,auto_now=False)
    updated=models.DateTimeField(auto_now_add=False,auto_now=True)

    def __str__(self):
        return self.order_id

orders/views.py
import time
from django.shortcuts import render,HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from carts.models import Cart
from .models import Order
from .utils import id_generator
from accounts.forms import UserAddressForm
from accounts.models import  UserAddress
from django.conf import settings

# Create your views here.
try:
    stripe_pub = settings.STRIPE_PUBLISHABLE_KEY
except Exception as e:
    raise NotImplementedError(str(e))


def orders(request):
    context={}
    template="orders/user.html"
    return render(request,template,context)

@login_required
def checkout(request):

    try:
        the_id=request.session['cart_id']
        cart=Cart.objects.get(id=the_id)

    except:
        the_id=None
        return HttpResponseRedirect(reverse("cart"))

    try:
        new_order=Order.objects.get(cart=cart)
    except Order.DoesNotExist:
        new_order=Order()
        new_order.cart=cart
        new_order.user=request.user
        new_order.order_id=id_generator()
        new_order.save()
    except:
        return HttpResponseRedirect(reverse("cart"))

    try:
        address_added=request.Get.get("address_added")
        print(address_added)
    except:
        address_added=None
    if address_added is None:
        address_form=UserAddressForm()
    else:
        address_form=None

    current_addresses=UserAddress.objects.filter(user=request.user)
    billing_addresses=UserAddress.objects.get_billing_addresses(user=request.user)

    if request.method== "POST":
        print(request.POST.get('stripeToken'))

    if new_order.status=="Finished":
        del request.session['cart_id']
        del request.session['items_total']

    context={
        'address_form':address_form,
        'current_addresses':current_addresses,
        'billing_addresses':billing_addresses,
        'stripe_pub': stripe_pub,
    }
    template="orders/checkout.html"
    return render(request,template,context)

templates/orders/checkout.html
{%extends "base.html"%}
<script>
{%block jquery%}
var stripe = Stripe('{{stripe_pub}}');

var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.on('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
}

{%endblock%}
</script>
{%block content%}
<div class="container">

  {% if address_form %}
  <div class="col-sm-6 float-right">
      <h3>Add New Shipping Addresses</h3>
      <hr/>
  <form method="POST" action="{% url 'ajax_add_user_address' %}?next=checkout">{%csrf_token%}
    {{address_form.as_p}}
  <input type="submit" name="btn btn-default" value="Add shipping address"/>
  </form>
  </div>
  {%endif%}


<form method="POST" action="" id="payment-form">{%csrf_token%}
{%if current_addresses%}
<div class="col-sm-6 ">
  <h3>Shipping Addresses</h3>
  <hr/>
  {% for address in current_addresses %}
  {%if request.user.userdefaultaddress.shipping.id == address.id %}
  <input type='radio' name='shipping_address' value='{{address.id}}' checked="checked"/> {{address.get_address}} <br/>
  {%else%}
  <input type='radio' name='shipping_address' value='{{address.id}}' /> {{address.get_address}} <br/>
  {% endif %}
  {%endfor%}
  </div>
{%endif%}

<br/>
<div class="row">
  {%if billing_addresses%}
  <div class="col-sm-6">
    <h3>Billing Addresses</h3>
    <hr/>
    {% for address in billing_addresses %}
    {%if request.user.userdefaultaddress.billing.id == address.id %}
    <input type='radio' name='billing_address' value='{{address.id}}' checked="checked"/> {{address.get_address}} <br/>
    {%else%}
    <input type='radio' name='billing_address' value='{{address.id}}' /> {{address.get_address}} <br/>
    {% endif %}
    {%endfor%}
  </div>
  {%endif%}
</div>

<br/>
  <h3>Credit Card Info</h3>
  <div class="sr-root">
  <div class="sr-main">
    <div class="sr-payment-form">
      <div class="sr-combo-inputs-row">
        <div class="sr-input sr-card-element StripeElement StripeElement--complete" id="card-element"><div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;"><iframe frameborder="0" allowtransparency="true" scrolling="no" name="__privateStripeFrame5" allowpaymentrequest="true" src="https://js.stripe.com/v3/elements-inner-card-88d2c1d509ed827c98931e4c04540fc7.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;apiKey=pk_test_51Guxm2ClRwhSe2klk5PB8zOQQiZdfw5SccJtUMojikdobn7EK5MmEKUCRNNJi7RxC2HFL8pUrvvs5OfgaCoCgH6S00WugakF46&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fpayments%2Faccept-a-payment&amp;controllerId=__privateStripeController1" title="Secure payment input frame" style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; user-select: none !important; height: 19.2px;"></iframe><input class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false" maxlength="1" style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;"></div></div>
      </div>
      <div class="sr-field-error" id="card-errors" role="alert">Your card number is incomplete.</div>
      <button class="submit" id="submit">
        <div class="spinner hidden" id="spinner"></div>
        <span id="button-text" class="">Pay Now</span><span id="order-amount"></span>
      </button>
      <button class="sr-pill fill-card"><i></i><span>Prefill card details</span></button>
    </div>
    <div class="sr-result hidden">
      <p>
        Success! Here's the <code>PaymentIntent</code> that was returned by the Stripe API.
        The <code>status</code> of <code>succeeded</code> indicates that the payment was completed successfully.
      </p>
      <pre class=" language-javascript"><code class=" language-javascript"></code></pre>
    </div>
  </div>
</div>

</form>
</div>
{%endblock%}

templates/orders/user.html
{%extends "base.html"%}
{%block content%}

{{user.order_set.all}}


{%endblock%}